# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1bc558b8470985fa5af4526037dfba32"
name = "QuoteCart Live"
application_url = "https://quote-cart-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,write_draft_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://quote-cart-production.up.railway.app/auth/callback",
  "https://quote-cart-production.up.railway.app/auth/shopify/callback",
  "https://quote-cart-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[app_proxy]
url = "https://quote-cart-production.up.railway.app/apps/quote"
prefix = "apps"
subpath = "quote"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true